### ISSUE TITLE
Disabled mac address field

### ISSUE THREAD

**Issue by lamebrain** [WildernessLabs/Netduino-Updater#18]
I have a brand new device that's never been initialized.  When selecting Netduino3 Ethernet, the MAC address field remains disabled

<img width="959" alt="screen shot 2018-04-14 at 2 15 46 pm" src="https://user-images.githubusercontent.com/1048330/38772570-984625d4-3fee-11e8-90a9-c38588317c4c.png">

**Comment by adrianstevens** [comment]
This should be fixed in 2.0.3

**Comment by adrianstevens** [comment]
this is fixed - closing
